name: generate-jsdoc
on: 
    push:
    workflow_dispatch:

jobs:
    jsdoc-job:
        runs-on: ubuntu-latest
        steps:
          - name: Get access to repo
            uses: actions/checkout@v4
          - name: Install Dependencies
            run: npm install
          - name: Generate JSDoc
            run: npx jsdoc -c ./.config/jsdoc.json
          - name: Commit JSDoc
            run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git add .
                git commit -m "Generate JSDoc"
          - name: Push JSDoc
            uses: ad-m/github-push-action@master
            with:
               github_token: ${{secrets.GITHUB_TOKEN}}
               force: true

       
