name: generate-jsdoc
on:
    push:    
    workflow_dispatch:

jobs:
    jsdoc-job:
        runs-on: ubuntu-latest
        steps:
           - name: JSDoc Action patch
             uses: zhennann/jsdoc-action@v1.2.1
             with:
                source_dir: ./js
                output_dir: ./docs/jsdoc
       
